define([], function() {
	var APPRECIATE = '/appreciate';
	var PROMOTE = '/promote';
	var ACCEPT = '/accept';
	var DENY = '/deny';
	var WITHDRAW = '/withdraw';
	var OUTSTANDING = '/outstanding';
	var EMAIL = '/email';
	var AUTHOR = '/author';
	var BACKER = '/backer';
	var ENABLE = '/enable';
	var DISABLE = '/disable';
	var SEND = '/send';
	var FLAG = '/flag';
	var CHANGE = '/change';
	var RESET = '/reset';
	var REMOVE = '/remove';
	var DELETE = '/delete';
	var ROLES = '/roles';
	var PENDING_ACTIONS = '/pending';
	var FINANCES = '/finances';
	var PAYMENT = '/payment';
	var PURCHASE = '/purchase';
	var CURRENCY = '/currency';
	var RESPONSE = '/response';
	var SUBSCRIPTION = '/subscription';
	var FOLLOWERS = '/followers';
	var FOLLOWEES = '/followees';
	var BLOCKED = '/blocked';
	var FEED = '/feed';
	var NOTIFICATIONS = '/notifications';
	var ID = '/{0}';
	
	var SHOW = '/show';
	
	var LOGIN = '/login';
	var REGISTER = '/register';
	var LOGOUT = '/logout';
	
	var OFFERS = '/offers';
	var BACKERS = '/backings';
	
	var POSTINGS = '/postings';
	var POSTINGS_ID = POSTINGS + ID;
	var COMMENTS = '/comments';
	var COMMENTS_ID = COMMENTS + ID;
	var USERS = '/users';
	var USERS_ID = USERS + ID;
	var TAGS = '/tags';
	var TAGS_ID = TAGS + ID;
	var EMAIL_ID = EMAIL + ID;
	
	var CURRENT = '/current';
	var PROFILE = '/profile';
	var HIDE = '/hide';
	var LOCATIONS = '/locations';
	var CONFIRMATION = '/confirmation';
	var PASSWORD = '/password';
	var SETTINGS = '/settings';
	
	var MESSAGES = '/messages';
	
	var RESOURCES = '/resources';
	
	return {
		LOGIN: LOGIN,
		LOGOUT: LOGOUT,
		REGISTER: REGISTER,
		
		CURRENT: CURRENT,
		CURRENT_DELETE_SEND: CURRENT + DELETE + SEND,
		CURRENT_DELETE: CURRENT + DELETE,
		CURRENT_ACCEPT: CURRENT + ACCEPT,
		ROLES: ROLES,
		PROFILE: PROFILE,
		RESPONSE: RESPONSE,
		LOCATIONS: LOCATIONS,
		LOCATIONS_REMOVE: LOCATIONS + REMOVE,
		CONFIRMATION: CONFIRMATION,
		CONFIRMATION_SEND: CONFIRMATION + SEND,
		EMAIL: EMAIL,
		EMAIL_CHANGE: EMAIL + CHANGE,
		EMAIL_PENDING_ACTION_CHANGE: EMAIL + PENDING_ACTIONS,
		PASSWORD: PASSWORD,
		PASSWORD_USERS_ID: PASSWORD + USERS_ID,
		PASSWORD_RESET: PASSWORD + RESET,
		SETTINGS: SETTINGS,
		
		FINANCES: FINANCES,
		
		PAYMENT: PAYMENT,
		PAYMENT_CHANGE: PAYMENT + CHANGE,
		PAYMENT_SEND: PAYMENT + SEND,
		PURCHASE: CURRENCY + PURCHASE,
		
		POSTINGS: POSTINGS,
		POSTINGS_CURRENT: CURRENT + POSTINGS,
		POSTINGS_ID: POSTINGS_ID,
		POSTINGS_COMMENTS: POSTINGS_ID + COMMENTS,
		POSTINGS_APPRECIATE: POSTINGS_ID + APPRECIATE,
		POSTINGS_PROMOTE: POSTINGS_ID + PROMOTE,
		POSTINGS_ENABLE: POSTINGS_ID + ENABLE,
		POSTINGS_DISABLE: POSTINGS_ID + DISABLE,
		POSTINGS_FLAG: POSTINGS_ID + FLAG,
		POSTINGS_EDIT: POSTINGS_ID + CHANGE,
		
		COMMENTS: COMMENTS,
		COMMENTS_CURRENT: CURRENT + COMMENTS,
		COMMENTS_ID: COMMENTS_ID,
		COMMENTS_COMMENTS: COMMENTS_ID + COMMENTS,
		COMMENTS_APPRECIATE: COMMENTS_ID + APPRECIATE,
		COMMENTS_PROMOTE: COMMENTS_ID + PROMOTE,
		COMMENTS_ENABLE: COMMENTS_ID + ENABLE,
		COMMENTS_DISABLE: COMMENTS_ID + DISABLE,
		COMMENTS_FLAG: COMMENTS_ID + FLAG,
		COMMENTS_EDIT: COMMENTS_ID + CHANGE,
		
		TAGS: TAGS,
		TAGS_ID: TAGS_ID,
		TAGS_COMMENTS: TAGS_ID + COMMENTS,
		
		USERS: USERS,
		USERS_ID: USERS_ID,
		USERS_APPRECIATION_RESPONSE: USERS_ID + RESPONSE,
		USERS_FLAG: USERS_ID + FLAG,
		USERS_RESPONSE: USERS_ID + RESPONSE,
		USERS_COMMENTS: USERS_ID + COMMENTS,
		USERS_FOLLOWEES: USERS_ID + FOLLOWEES,
		USERS_FOLLOWERS: USERS_ID + FOLLOWERS,
		USERS_FEED: USERS_ID + FEED,
		
		FEED: FEED,
		NOTIFICATIONS: NOTIFICATIONS,
		
		MESSAGES: MESSAGES,
		CONVERSATION: MESSAGES + USERS_ID,
		CONVERSATION_MESSAGES: MESSAGES + USERS_ID + MESSAGES,
		CONVERSATION_FLAG: MESSAGES + USERS_ID + FLAG,
		CONVERSATION_SHOW: MESSAGES + USERS_ID + SHOW,
		
		SUBSCRIPTION: SUBSCRIPTION,
		
		FOLLOWERS: FOLLOWERS,
		FOLLOWERS_ID: FOLLOWERS + USERS_ID,
		FOLLOWEES: FOLLOWEES,
		FOLLOWEES_ID: FOLLOWEES + USERS_ID,
		
		BLOCKED: BLOCKED,
		BLOCKED_ID: BLOCKED + USERS_ID,
		
		OFFERS: OFFERS,
		OFFERS_ID: OFFERS + USERS_ID,
		OFFERS_ACCEPT: OFFERS + USERS_ID + ACCEPT,
		OFFERS_DENY: OFFERS + USERS_ID + DENY,
		OFFERS_OUTSTANDING: OFFERS + OUTSTANDING,
		OFFERS_OUTSTANDING_ID: OFFERS + OUTSTANDING + USERS_ID,
		OFFERS_OUTSTANDING_WITHDRAW: OFFERS + OUTSTANDING + USERS_ID + WITHDRAW,
		OFFERS_EMAIL_ACCEPT: OFFERS + USERS_ID + EMAIL + ACCEPT,
		OFFERS_EMAIL_DENY: OFFERS + USERS_ID + EMAIL + DENY,
		OFFERS_EMAIL: OFFERS + EMAIL,
		OFFERS_EMAIL_OUTSTANDING: OFFERS + OUTSTANDING + EMAIL,
		OFFERS_EMAIL_OUTSTANDING_ID: OFFERS + OUTSTANDING + EMAIL_ID,
		OFFERS_EMAIL_OUTSTANDING_WITHDRAW: OFFERS + OUTSTANDING + EMAIL_ID + WITHDRAW,
		
		BACKERS: BACKERS,
		BACKERS_ID: BACKERS + USERS_ID,
		BACKERS_OUTSTANDING: BACKERS + OUTSTANDING,
		BACKERS_OUTSTANDING_ID: BACKERS + OUTSTANDING + USERS_ID,
		
		CORS_PROXY_HTML: RESOURCES + '/corsProxy.html',
		CORS_PROXY_JS: RESOURCES + '/corsProxy.min.js'
	};
});