define([], function() {
	return {
		TIME_OPTION_HOUR: 'HOUR',
		TIME_OPTION_DAY: 'DAY',
		TIME_OPTION_MONTH: 'MONTH',
		TIME_OPTION_YEAR: 'YEAR',
		TIME_OPTION_ALLTIME: 'ALLTIME',
		SORT_OPTION_VALUE: 'VALUE',
		SORT_OPTION_PROMOTION: 'PROMOTION',
		SORT_OPTION_COST: 'COST',
		DIRECTION_ASCENDING: 'ascending',
		DIRECTION_DESCENDING: 'descending',
		
		FLAG_REASON_ILLICIT: 'ILLICIT',
		FLAG_REASON_VIOLATION: 'VIOLATION',
		FLAG_REASON_SPAM: 'SPAM',
		FLAG_REASON_PLAGIARISM: 'PLAGIARISM'
	};
});